# Generated by Django 6.1.1 on 2026-10-02 15:16

from django.utils import timezone
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


def copy_legacy_users(apps, schema_editor):
    connection = schema_editor.connection
    existing_tables = set(connection.introspection.table_names())
    if "auth_user" not in existing_tables:
        return

    User = apps.get_model("authentication", "User")
    alias = connection.alias
    user_table = connection.ops.quote_name("auth_user")
    fields = (
        "id",
        "password",
        "last_login",
        "is_superuser",
        "username",
        "first_name",
        "last_name",
        "email",
        "is_staff",
        "is_active",
        "date_joined",
    )
    quoted_fields = ", ".join(connection.ops.quote_name(field) for field in fields)

    with connection.cursor() as cursor:
        cursor.execute(f"SELECT {quoted_fields} FROM {user_table}")
        legacy_users = cursor.fetchall()

    def preserve_utc(value):
        if value is not None and timezone.is_naive(value) and connection.timezone:
            return timezone.make_aware(value, connection.timezone)
        return value

    User.objects.using(alias).bulk_create(
        [
            User(
                id=row[0],
                password=row[1],
                last_login=preserve_utc(row[2]),
                is_superuser=row[3],
                username=row[4],
                first_name=row[5],
                last_name=row[6],
                email=row[7],
                is_staff=row[8],
                is_active=row[9],
                date_joined=preserve_utc(row[10]),
                account_type="customer",
            )
            for row in legacy_users
        ]
    )

    relations = (
        ("auth_user_groups", User.groups.through),
        ("auth_user_user_permissions", User.user_permissions.through),
    )
    for legacy_table, relation_model in relations:
        target_table = relation_model._meta.db_table
        if legacy_table not in existing_tables or target_table not in existing_tables:
            continue

        quoted_source = connection.ops.quote_name(legacy_table)
        quoted_target = connection.ops.quote_name(target_table)
        with connection.cursor() as cursor:
            cursor.execute(
                f"INSERT INTO {quoted_target} (user_id, {connection.ops.quote_name('group_id' if legacy_table == 'auth_user_groups' else 'permission_id')}) "
                f"SELECT user_id, {connection.ops.quote_name('group_id' if legacy_table == 'auth_user_groups' else 'permission_id')} FROM {quoted_source}"
            )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('account_type', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff')], default='customer', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=24)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RunPython(copy_legacy_users, migrations.RunPython.noop),
    ]
